# Generated by Django 3.2 on 2023-05-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230529_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
